git_account_name = "born-to-be-mad"
git_branch_name = "develop"
git_repository_name = "azure-data-engineering"
git_root_folder = "/datafactory"
git_root_synapse_folder = "/synapse"
git_url = "https://github.com"